inherit_from: .rubocop_todo.yml
require: rubocop-rspec
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - "vendor/**/*"
    - "log/**/*"
Metrics/AbcSize:
  Max: 64
Metrics/LineLength:
  Max: 180
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 60
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*.rb'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
Documentation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/BlockDelimiters:
  Exclude:
    - 'config/routes.rb'
Style/IndentHash:
  EnforcedStyle: consistent
Style/IndentArray:
  EnforcedStyle: consistent
Style/DoubleNegation:
  Enabled: false
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/SubjectStub:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 20
RSpec/VerifiedDoubles:
  Enabled: false
