require: rubocop-rspec
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - "vendor/**/*"
    - "log/**/*"
Metrics/AbcSize:
  Max: 64
Metrics/LineLength:
  Max: 180
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 60
Documentation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/BlockDelimiters:
  Exclude:
    - 'config/routes.rb'
