language: ruby
sudo: required
rvm:
  - 2.3.0
node_js:
  - 5.10
cache: bundler
env:
  - DATABASE_URL=mysql2://root:@127.0.0.1/e2e_tester_test
before_script:
  - mysql -u root -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS e2e_tester_test;'
  - npm install
  - bundle exec rake bower:install
script:
  - bundle exec rake
  - bundle exec rails db:environment:set RAILS_ENV=test; bundle exec rails db:drop db:create db:migrate db:seed
services:
  - docker
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
notifications:
  email: false
