service:
  host: <%= ENV['SERVICE_HOST'] || 'TBA' %>
  protocol: 'http'
admin:
  email_domain: '.*'
browserstack:
  username: <%= ENV['BROWSERSTACK_USERNAME'] || 'TBA' %>
  password: <%= ENV['BROWSERSTACK_PASSWORD'] || 'TBA' %>
omniauth:
  google:
    app_id: <%= ENV['OMNIAUTH_GOOGLE_APP_ID'] || 'TBA' %>
    app_secret: <%= ENV['OMNIAUTH_GOOGLE_APP_SECRET'] || 'TBA' %>
redis:
  sidekiq:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || 'TBA' %>
  session_store:
    url: <%= ENV['REDIS_SESSION_STORE_URL'] || 'TBA' %>
storage:
  fog_credentials:
    ## Local storage
    provider: "Local"
    local_root: "./public/system"
    endpoint: "//<%= ENV['SERVICE_HOST'] || 'TBA' %>/system"
  fog_directory: 'docker'
secret_key_base: '0c4e7a0d33198bb3b77d71308ba5090b8988c30cdbc6be398d81caa86ceee8cfb81c27a72b4cf875a7c91927182ebb9e5b62fa7010401f5033be758dae6f5369'
