service:
  host: 'TBA'
  protocol: 'http'
mailer:
  sender:
    default: 'foo@example.com'
secret_key_base: 'TBA'
session:
  key: '_e2etstr'
  secure: false
  expire_after: <%= 90.minutes %>
browserstack:
  username: 'TBA'
  password: 'TBA'
bugsnag:
  api_key: 'TBA'
  release_stages:
    - 'production'
storage:
  fog_credentials:
    ## S3
    # provider: "AWS"
    # aws_access_key_id: "ABCDEFG123456"
    # aws_secret_access_key: "ABCDEFG123456"
    # host: "aws.s3.amazonaws.com"
    # path_style: true
    ## Local storage
    # provider: "Local"
    # local_root: "./public/system"
    # endpoint: "//e2e-tester.dev/system"
  fog_directory: 'TBA' # Directory/Bucket to put files
  fog_attributes:
    'Cache-Control': 'max-age=<%= 10.years.to_i %>'
  root: # If you want to change the root in the directory
paperclip:
  cache_max_age:
    image: <%= 10.year.to_i %>
service:
  admin: true
  sidekiq: true
omniauth:
  google:
    app_id: 'TBA'
    app_secret: 'TBA'
admin:
  email_domain: 'TBA'
redis:
  sidekiq:
    url: 'TBA'
    namespace: 'e2e-tester-sidekiq'
  session_store:
    url: 'TBA'
    namespace: 'e2e-tester-session'
    expire_after: <%= 60.minutes.to_i %>
logger:
  color: false
  format: 'detail'
  default:
    level: <%= Logger::INFO %>
  active_record:
    level: <%= Logger::INFO %>
  action_controller:
    level: <%= Logger::INFO %>
  action_mailer:
    level: <%= Logger::INFO %>
