application:
  host: <%= ENV['SERVICE_HOST'] || 'TBA' %>
  protocol: 'http'
mailer:
  type: 'letter_opener_web'
  sender:
    default: <%= ENV['MAILER_SENDER_DEFAULT'] || 'foo@example.com' %>
secret_key_base: 'TBA'
session:
  key: '_e2etstr'
  secure: false
  expire_after: <%= 90.minutes %>
browserstack:
  username: <%= ENV['BROWSERSTACK_USERNAME'] || 'TBA' %>
  password: <%= ENV['BROWSERSTACK_PASSWORD'] || 'TBA' %>
bugsnag:
  api_key: <%= ENV['BUGSNAG_API_KEY'] || 'TBA' %>
  release_stages:
    - 'production'
storage:
  fog_credentials:
    ## S3
    # provider: 'AWS'
    # region: 'us-west-1'
    # scheme: 'https'
    # aws_access_key_id: 'ABCDEFG123456'
    # aws_secret_access_key: 'ABCDEFG123456'
    ## Local storage
    # provider: "Local"
    # local_root: "./public/system"
    # endpoint: "//<%= ENV['SERVICE_HOST'] || 'TBA' %>/system"
  fog_directory: 'storage' # Directory/Bucket to put files
  fog_options:
    cache_control: 'max-age=<%= 10.years.to_i %>'
  root: # If you want to change the root in the directory
paperclip:
  cache_max_age:
    image: <%= 10.year.to_i %>
service:
  admin: true
  sidekiq: true
omniauth:
  google:
    app_id: <%= ENV['OMNIAUTH_GOOGLE_APP_ID'] || 'TBA' %>
    app_secret: <%= ENV['OMNIAUTH_GOOGLE_APP_SECRET'] || 'TBA' %>
admin:
  email_format: '.*'
redis:
  sidekiq_client:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    namespace: 'e2e-tester-sidekiq'
    size: <%= ENV['REDIS_SIDEKIQ_SIZE'] %>
  sidekiq_server:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    namespace: 'e2e-tester-sidekiq'
    size: <%= ENV['REDIS_SIDEKIQ_SIZE'] %>
  session_store:
    url: <%= ENV['REDIS_SESSION_STORE_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    namespace: 'e2e-tester-session'
    expire_after: <%= 60.minutes.to_i %>
    maxclients: <%= ENV['REDIS_SESSION_STORE_SIZE'] %>
logger:
  color: false
  format: 'detail'
  default:
    io_type: 'file'
    level: <%= Logger::INFO %>
  active_record:
    io_type: 'file'
    level: <%= Logger::INFO %>
  action_controller:
    io_type: 'file'
    level: <%= Logger::INFO %>
  action_mailer:
    io_type: 'file'
    level: <%= Logger::INFO %>
mandrill:
  username: <%= ENV['MANDRILL_USERNAME'] || 'TBA' %>
  api_key: <%= ENV['MANDRILL_API_KEY'] || 'TBA' %>
mailgun:
  username: <%= ENV['MAILGUN_USERNAME'] || 'TBA' %>
  password: <%= ENV['MAILGUN_PASSWORD'] || 'TBA' %>
google:
  analytics:
    tracking_id: <%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] || 'TBA' %>
