service:
  host: 'localhost:3000'
  protocol: 'http'
admin:
  email_domain: '.*'
logger:
  color: true
  format: 'simple'
  default:
    io_type: 'file'
    level: <%= Logger::DEBUG %>
  active_record:
    io_type: 'file'
    level: <%= Logger::DEBUG %>
  action_controller:
    io_type: 'file'
    level: <%= Logger::DEBUG %>
  action_mailer:
    io_type: 'file'
    level: <%= Logger::DEBUG %>
storage:
  fog_credentials:
    ## Local storage
    provider: "Local"
    local_root: "./public/system"
    endpoint: "//localhost:3000/system"
  fog_directory: 'dev'
secret_key_base: 'a35b5385a72ea7d21a82cdf74f81e9c2f1be5606b8cbcd3dcb29cd46e346905b8ee29062b3913fecc91f28bb0c0f4f0271cf5114d383bf560a0ffe5a31db669a'
