service:
  host: <%= ENV['SERVICE_HOST'] || 'TBA' %>
  protocol: <%= ENV['SERVICE_PROTOCOL'] || 'http' %>
admin:
  email_domain: <%= ENV['ADMIN_EMAIL_DOMAIN'] || 'TBA' %>
omniauth:
  google:
    app_id: <%= ENV['OMNIAUTH_GOOGLE_APP_ID'] || 'TBA' %>
    app_secret: <%= ENV['OMNIAUTH_GOOGLE_APP_SECRET'] || 'TBA' %>
bugsnag:
  api_key: 'TBA'
browserstack:
  username: <%= ENV['BROWSERSTACK_USERNAME'] || 'TBA' %>
  password: <%= ENV['BROWSERSTACK_PASSWORD'] || 'TBA' %>
storage:
  fog_credentials:
    provider: "AWS"
    region: 'TBA'
    aws_access_key_id: 'TBA'
    aws_secret_access_key: 'TBA'
  fog_directory: 'TBA'
  root: 'TBA'
redis:
  sidekiq:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || ENV['REDIS_URL'] || 'TBA' %>
  session_store:
    url: <%= ENV['REDIS_SESSION_STORE_URL'] || ENV['REDIS_URL'] || 'TBA' %>
mandrill:
  enabled: true
  username: 'TBA'
  api_key: 'TBA'
logger:
  color: true
  format: 'simple'
  default:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  active_record:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  action_controller:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  action_mailer:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
secret_key_base: 'TBA'
