service:
  host: <%= ENV['SERVICE_HOST'] || 'TBA' %>
  protocol: <%= ENV['SERVICE_PROTOCOL'] || 'http' %>
admin:
  email_format: <%= ENV['ADMIN_EMAIL_FORMAT'] || 'TBA' %>
omniauth:
  google:
    app_id: <%= ENV['OMNIAUTH_GOOGLE_APP_ID'] || 'TBA' %>
    app_secret: <%= ENV['OMNIAUTH_GOOGLE_APP_SECRET'] || 'TBA' %>
bugsnag:
  api_key: <%= ENV['BUGSNAG_API_KEY'] || 'TBA' %>
browserstack:
  username: <%= ENV['BROWSERSTACK_USERNAME'] || 'TBA' %>
  password: <%= ENV['BROWSERSTACK_PASSWORD'] || 'TBA' %>
storage:
  fog_credentials:
    provider: "AWS"
    region: 'us-west-1'
    aws_access_key_id: <%= ENV['STORAGE_AWS_ACCESS_KEY_ID'] || 'TBA' %>
    aws_secret_access_key: <%= ENV['STORAGE_AWS_ACCESS_KEY'] || 'TBA' %>
  fog_directory: <%= ENV['STORAGE_FOG_DIRECTORY'] || 'TBA' %>
  root: <%= ENV['STORAGE_ROOT'] || 'TBA' %>
redis:
  sidekiq_client:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    size: <%= ENV['REDIS_SIDEKIQ_SIZE'] %>
  sidekiq_server:
    url: <%= ENV['REDIS_SIDEKIQ_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    size: <%= ENV['REDIS_SIDEKIQ_SIZE'] %>
  session_store:
    url: <%= ENV['REDIS_SESSION_STORE_URL'] || ENV['REDIS_URL'] || 'TBA' %>
    maxclients: <%= ENV['REDIS_SESSION_STORE_SIZE'] %>
mailer:
  type: <%= ENV['MAILER_TYPE'] || 'TBA' %>
  sender:
    default: <%= ENV['MAILER_SENDER_DEFAULT'] || 'foo@example.com' %>
mandrill:
  username: <%= ENV['MANDRILL_USERNAME'] || 'TBA' %>
  api_key: <%= ENV['MANDRILL_API_KEY'] || 'TBA' %>
mailgun:
  username: <%= ENV['MAILGUN_USERNAME'] || 'TBA' %>
  password: <%= ENV['MAILGUN_PASSWORD'] || 'TBA' %>
logger:
  color: true
  format: 'simple'
  default:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  active_record:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  action_controller:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
  action_mailer:
    io_type: <%= ENV['LOGGER_IO_TYPE'] || 'file' %>
secret_key_base: 'TBA'
