application:
  host: 'example.com'
  protocol: 'http'
admin:
  email_format: '.*@example.com'
redis:
  sidekiq_client:
    url: redis://localhost:6379/2
  sidekiq_server:
    url: redis://localhost:6379/2
  session_store:
    url: redis://localhost:6379/1
secret_key_base: '70100f06ac292510739ffef99ebc333fa52b3ec4ea7c969f3997a9fdd84d66fd64b92da4c52c569d22dc7cbc0a446cddf77c8e4c28940e7894676077cbba3d8c'
